const mongoose = require('mongoose');
const uniqueValidator = require('mongoose-unique-validator'); /* package to make sure that sauce name is unique in database */

const sauceSchema = mongoose.Schema({
  /* sauce id is automatically generated by MongoDB */
  userId: { type: String, required: true },
  name: { type: String,required:true, unique: true},
  manufacturer: { type: String, required: true },
  description: { type: String, required: true},
  mainPepper: { type: String, required: true},
  heat: { type: Number, required: true },
  imageUrl: { type: String, required: true },
  likes: { type: Number },
  dislikes: { type: Number },
  usersLiked: { type: [String] },
  usersDisliked: { type: [String] },
})

module.exports = mongoose.model('Sauce', sauceSchema) ; 
