const mongoose = require('mongoose');
const uniqueValidator = require('mongoose-unique-validator');  /* package to make sure that email is unique in database */

const userSchema = mongoose.Schema({
   /* user id is automatically generated by MongoDB */
   email: {
    type: String,
    unique: true,
    required: [true, "Veuillez entrer votre adresse email"],
  },
  password: { /* password will be verifie in routes */
    type: String,
    required: [true, "Veuillez choisir un mot de passe"],
  }
});

userSchema.plugin(uniqueValidator);

module.exports = mongoose.model('User', userSchema);
